name: Tests

on: [push, pull_request]

jobs:
  build:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction
          python -m spacy download en_core_web_sm
      - name: Run Unit Tests
        run: |
          pytest --doctest-modules --cov=rake_spacy --cov-report=xml --cov-report=term tests/ rake_spacy/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
