name: Type Check

on: [push, pull_request]

jobs:
  build:
    name: "Type Check Code Base"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: "Type Check with Mypy"
        run: |
          ls -la
